### ISSUE TITLE
Issue running lenet300 model

### ISSUE THREAD

**Issue by GeoBouz** [iree-org/iree-bare-metal-arm#347]
Hello!

I am trying to run a small model (lenet300) on STM32F407 and measure the time but I get segmentation error:
[0/2] Re-checking globbed directories...
[124/135] Generating simple_embedding_test_bytecode_module_vmvx.vmfb
FAILED: samples/simple_embedding/simple_embedding_test_bytecode_module_vmvx.vmfb /home/gbouzikas/Thesis/iree-bare-metal-arm/build/samples/simple_embedding/simple_embedding_test_bytecode_module_vmvx.vmfb 
cd /home/gbouzikas/Thesis/iree-bare-metal-arm/build/samples/simple_embedding && /home/gbouzikas/Thesis/iree-bare-metal-arm/build-iree-host-install/bin/iree-compile --output-format=vm-bytecode --iree-hal-target-backends=vmvx /home/gbouzikas/Thesis/iree-bare-metal-arm/third_party/iree/samples/simple_embedding/lenet300.mlir -o simple_embedding_test_bytecode_module_vmvx.vmfb
warning: <unknown>:0:0: stack frame size (1099511627768) exceeds limit (4294967295) in function '__truncsfhf2'
Segmentation fault (core dumped)
[127/135] Building C object third_party/iree/runtime/src/iree/vm/bytecode/CMakeFiles/iree_vm_bytecode_module.objects.dir/disassembler.c.obj
ninja: build stopped: subcommand failed.

Do you have any idea what may cause the issue?

I atach the tflite, the mlir
 and the code I run files.
[lenet300.zip](https://github.com/user-attachments/files/17229050/lenet300.zip)

Thank you in advance.

**Comment by marbre** [comment]
> warning: :0:0: stack frame size (1099511627768) exceeds limit (4294967295) in function '__truncsfhf2'

Seems to be your issue. In general, if you want to optimize and create a small model, make use of the llvm-cpu backend and don't go for vmvx. See https://iree.dev/guides/deployment-configurations/bare-metal/. There are several samples that target `llvm-cpu` and further reduce the memory footprint by using EmitC.

**Comment by GeoBouz** [comment]
Ok I will try that. Thank you very much!

**Comment by marbre** [comment]
Similar to #348, I would try to compile and run on the "high mem" config.

**Comment by marbre** [comment]
@GeoBouz is it okay to close this?

**Comment by GeoBouz** [comment]
Hi @marbre. Yes thank you!

**Comment by GeoBouz** [comment]
Hi @marbre! Is there any example using target llvm-cpu and EmitC? Thank you.

**Comment by marbre** [comment]
> Hi [@marbre](https://github.com/marbre)! Is there any example using target llvm-cpu and EmitC? Thank you.

Hi, @GeoBouz. There are several samples that make use of EmitC (`--output-format=vm-c`) + llvm-cpu (`--iree-hal-target-backends=llvm-cpu`):
* `simple_vec_mul_int_bytecode_static_c`
* `simple_vec_mul_int_bytecode_static_inline_c`
* `sample_static_library_c`

**Comment by GeoBouz** [comment]
I tried this but with --iree-input-type=tosa it doesnt work.
