### ISSUE TITLE
Issue running kws_ref model

### ISSUE THREAD

**Issue by GeoBouz** [iree-org/iree-bare-metal-arm#348]
Hello!

I am trying to run a small model (kws_ref) on STM32F407 and measure the time. It compiles successfully but when I try to test it with renode I get this outcome:

15:22:23.9715 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x200243F0, value 0x0.
15:22:23.9715 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x200243F4, value 0x0.
15:22:23.9716 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x200243F8, value 0x0.
15:22:23.9716 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x200243FC, value 0x0.
15:22:23.9716 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024400, value 0x0.
15:22:23.9716 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024404, value 0x0.
15:22:23.9717 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x20024408, value 0x0.
15:22:23.9717 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x2002440C, value 0x0.
15:22:23.9717 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024410, value 0x0.
15:22:23.9717 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024414, value 0x0.
15:22:23.9717 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x20024418, value 0x0.
15:22:23.9718 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x2002441C, value 0x0.
15:22:23.9718 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024420, value 0x0.
15:22:23.9718 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024424, value 0x0.
15:22:23.9718 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x20024428, value 0x0.
15:22:23.9719 [WARNING] sysbus: [cpu: 0x80005FE] WriteDoubleWord to non existing peripheral at 0x2002442C, value 0x0.
15:22:23.9719 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024430, value 0x0.
15:22:23.9719 [WARNING] sysbus: [cpu: 0x8000602] WriteDoubleWord to non existing peripheral at 0x20024434, value 0x0.
15:22:23.9719 [WARNING] sysbus: [cpu: 0x800060A] WriteDoubleWord to non existing peripheral at 0x20024438, value 0x0.
15:22:23.9720 [WARNING] sysbus: [cpu: 0x800060A] WriteDoubleWord to non existing peripheral at 0x2002443C, value 0x0.
15:22:23.9720 [WARNING] sysbus: [cpu: 0x800060A] WriteDoubleWord to non existing peripheral at 0x20024440, value 0x0.
15:22:23.9720 [WARNING] sysbus: [cpu: 0x0] ReadByte from non existing peripheral at 0x0.
15:22:23.9720 [ERROR] cpu: CPU abort [PC=0x0]: Trying to execute code outside RAM or ROM at 0x00000000.

Do you know what may be the issue?

The code I run and the tflite/mlir files:
[kws_ref_model.zip](https://github.com/user-attachments/files/17229280/kws_ref_model.zip)

Thank you in advance.

**Comment by marbre** [comment]
Seems like an out-of-memory issue to me. You could try to build for the `stm32f4xx` and test with `stm32f4xx-highmem` in Renode to see if that might be the issue.

**Comment by GeoBouz** [comment]
I built for this build you mentioned and now there is another problem during the test with renonde:
Starting emulation...
18:19:26.3438 [INFO] cpu: Guessing VectorTableOffset value to be 0x8000000.
18:19:26.3449 [WARNING] cpu: Tried to set VTOR address at 0x8000000 which does not lay in memory. Aborted.
18:19:26.3483 [WARNING] sysbus: ReadDoubleWord from non existing peripheral at 0x4.
18:19:26.3484 [WARNING] sysbus: ReadDoubleWord from non existing peripheral at 0x0.
18:19:26.3484 [ERROR] cpu: PC does not lay in memory or PC and SP are equal to zero. CPU was halted.
18:19:26.3498 [INFO] cpu: Setting initial values: PC = 0x0, SP = 0x0.
18:19:26.3501 [WARNING] cpu: Patching PC 0x0 for Thumb mode.
18:19:26.3511 [INFO] STM32F4XX: Machine started.

**Comment by GeoBouz** [comment]
Yes I am using configure_build.sh cmsis stm32f407

**Comment by marbre** [comment]
> configure_build.sh cmsis stm32f407

Try with `configure_build.sh cmsis stm32f4xx` instead to use in the linker script for the changed memory layout.

**Comment by GeoBouz** [comment]
Yes you are right, I forgot to change it there. Now it works correctly! Thank you very much!!

**Comment by marbre** [comment]
> Yes you are right, I forgot to change it there. Now it works correctly! Thank you very much!!

In that case it is indeed an out-of-memory issue (that is what we have created that config for). So unfortunately you only have the option to try to reduce the amount of used memory (see the bare-metal docs) or to switch the platform if you cannot tune the model itself. Is it okay if I close this issue?

**Comment by GeoBouz** [comment]
Yes its ok to close the issue. Thanks again!
